student_names=("darshan","punith","akhilesh","darshan","dhanush","hruthik","chethan","pavan","jashwanth","lohith","harsha")
print(student_names)
print(student_names[0])
print(student_names)

print(student_names.count("darshan"))
#print(student_names.append("ram"))
#print(student_names.remove("punth"))
#print(student_names.pop())
#print(student_names)

print("set")
student_names1={"darshan","punith","akhilesh","darshan","dhanush","hruthik","chethan","pavan","jashwanth","lohith","harsha"}
print(student_names1)
print(student_names1.add("ram"))
print(student_names1)
#print(student_names1.append("ram"))
print(student_names1)
print(student_names1.remove("punith"))
print(student_names1)
print(student_names1.pop())
print(student_names1)
