name=input("enter your name:")
print("my name is: ",name)
print(type(name))
userId=input("enter your user id:")
print("my userId is: ",userId)
print(type(userId))
age=int(input("enter your age:"))
print("my age is: ",age)
print(type(age))
Email=input("enter your email:")
print("my Email is: ",Email)
print(type(Email))
Ambition=input("ener your ambition:")
print("my Ambition is: ",Ambition)
print(type(Ambition))
hobies=input("enter hobies:").split()
print(hobies)


